apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: petclinic
    denyall: ingress
  name: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      run: petclinic
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: petclinic
    spec:
      containers:
      - image: eoghank/tbspetclinic:latest
        name: petclinic
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
